server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_ORDER}
    username: ${SPRING_DATASOURCE_USERNAME_ORDER}
    password: ${SPRING_DATASOURCE_PASSWORD_ORDER}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  username: ${KAFKA_USERNAME}
  password: ${KAFKA_PASSWORD}
  security-protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_SSL}
  sasl-mechanism: ${KAFKA_SASL_MECHANISM:SCRAM-SHA-256}
  properties:
    security.protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_SSL}
    sasl.mechanism: ${KAFKA_SASL_MECHANISM:SCRAM-SHA-256}
    sasl.jaas.config: >
      org.apache.kafka.common.security.scram.ScramLoginModule required
      username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: INFO
