server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_ORDER}
    username: ${SPRING_DATASOURCE_USERNAME_ORDER}
    password: ${SPRING_DATASOURCE_PASSWORD_ORDER}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: INFO
